// Regression checks for the real embedded game. Run: node tests/isla-brava.cjs
const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert');
const html=fs.readFileSync(path.join(__dirname,'..','isla-brava.html'),'utf8');
const source=html.match(/<script>([\s\S]*?)<\/script>/)[1];new vm.Script(source);
function boot(options={}){
 const elements=new Map(),events=new Map();let raf,time=0,shaderChecks=0;
 function classes(){const s=new Set();return {add:k=>s.add(k),remove:k=>s.delete(k),contains:k=>s.has(k),toggle:(k,value)=>{const add=value===undefined?!s.has(k):value;add?s.add(k):s.delete(k);}};}
 const context2d=new Proxy({},{get:()=>()=>{},set:()=>true});
 const gl=new Proxy({getExtension:()=>({vertexAttribDivisorANGLE(){},drawArraysInstancedANGLE(){}}),getShaderParameter:()=>!options.failHigh||++shaderChecks<=2,getProgramParameter:()=>true,getAttribLocation:()=>0,getUniformLocation:()=>({}),createBuffer:()=>({}),createProgram:()=>({}),createShader:()=>({}),uniformMatrix4fv:(location,transpose,data)=>assert(Array.from(data).every(Number.isFinite),'Finite camera matrix'),bufferData:(target,data)=>{if(data&&data.length)for(let i=0;i<data.length;i++)assert(Number.isFinite(data[i]),'Finite render geometry');}},{get:(o,k)=>k in o?o[k]:(/^[A-Z_]+$/.test(k)?0:()=>{})});
 const panels={avatars:['close-avatars','avatar-0','avatar-1','avatar-2'],'pause-screen':['graphics-pause-medium','graphics-pause-high','resume','back-menu'],'boss-preview':['close-boss-preview'],result:['replay','result-menu']};
 let document;
 function element(id,tag='DIV'){if(!elements.has(id))elements.set(id,{id,tagName:tag,style:{},hidden:false,textContent:'',attributes:{},events:new Map(),classList:classes(),captures:new Set(),addEventListener(n,fn){if(!this.events.has(n))this.events.set(n,[]);this.events.get(n).push(fn);},setAttribute(n,v){this.attributes[n]=String(v);},getAttribute(n){return this.attributes[n]??null;},append(){},replaceChildren(){},remove(){},focus(){document.activeElement=this;},setPointerCapture(id){this.captures.add(id);},releasePointerCapture(id){this.captures.delete(id);},hasPointerCapture(id){return this.captures.has(id);},getBoundingClientRect:()=>({left:0,top:0,width:112,height:112}),querySelectorAll:()=> (panels[id]||[]).map(id=>element(id,'BUTTON')),querySelector:selector=>element(id+'-'+selector,'SPAN'),getContext:()=>id==='world'?gl:context2d});return elements.get(id);}
 for(const id of html.matchAll(/<button[^>]*id="([^"]+)"/g))element(id[1],'BUTTON');
 const add=(n,fn)=>{if(!events.has(n))events.set(n,[]);events.get(n).push(fn);};
 document={getElementById:element,createElement:tag=>element('generated',tag.toUpperCase()),addEventListener:add,activeElement:null,hidden:false,body:{classList:classes()}};
 const window={addEventListener:add};
 const augmented=source.replace(/\}\)\(\);\s*$/,`window.qa={enterCave,showBossPreview,updateBoss,hitBoss,combatTargets,bossSet:fields=>Object.assign(boss,fields),defeat:()=>hitMonster(monsters.find(m=>m.alive)),openShop,closeShop,buyArmor,upgradeWeapon,nearestNPC,npcAccessible,damage,xp:value=>experience=value,gearMesh:()=>{const blocks=[];avatarModel(blocks,player,selectedAvatar,0,false,armor);return blocks;},segmentBox,cameraSolids,start,pause,resume,menu,attack,update,render,moveBody,blocked,updateWeapons,updateMedkits,previewAvatar,weaponFor,showAvatars,chooseAvatar,frame,mapPosition,hitMonster,segmentRect, resetMedkits, set:(fields)=>Object.assign(player,fields), avatar:i=>{selectedAvatar={...avatars[i]};avatarLabel();},mobs:points=>monsters=points.map(([x,z])=>({x,z,y:0,yaw:0,alive:true,color:C.red,speed:0,phase:0,attack:0,homeX:x,homeZ:z})),get:()=>({state,region,meshSize:dynamic.length,boss:boss?{...boss}:null,hazards:bossHazards.map(h=>({...h})),intro:caveIntro,score,goalScore:goalScore(),experience,weaponLevel,armor:[...armor],npcs:NPCS,shop:shopNPC?{...shopNPC}:null,worldTime,health:player.health,elapsed,player:{...player},camera:[...camera],cooldown:attackCooldown,attackTime,joy:{...joy},joyId,drag:cameraDrag?{...cameraDrag}:null,bolts:projectiles.map(p=>({...p})),pending:pendingHammer?{...pendingHammer}:null,kits:medkits.map(k=>({...k})),forts:FORTS,walls,colliders,lost:typeof rendererLost!=='undefined'?rendererLost:false}), ai:()=>{const m=combatTargets().filter(m=>m.alive).sort((a,b)=>Math.hypot(a.x-player.x,a.z-player.z)-Math.hypot(b.x-player.x,b.z-player.z))[0];if(!m||state!=='playing')return;keys.clear();const dx=m.x-player.x,dz=m.z-player.z;if(Math.hypot(dx,dz)>weaponFor().range*.75+(m.radius||0)*.65){const ix=Math.cos(cameraYaw)*dx-Math.sin(cameraYaw)*dz,iz=-Math.sin(cameraYaw)*dx-Math.cos(cameraYaw)*dz;if(Math.abs(ix)>.3)keys.add(ix>0?'KeyD':'KeyA');if(Math.abs(iz)>.3)keys.add(iz>0?'KeyW':'KeyS');}if(player.y===0&&player.health<60)jump();attack();update(1/60);if((++botFrame)%10===0)render();}};})();`);
 const testSource=augmented.replace('defeat:()=>hitMonster(monsters.find(m=>m.alive))','defeat:()=>{const m=monsters.find(m=>m.alive)||{x:player.x,z:player.z,alive:true,color:C.red};hitMonster(m)}').replace('window.qa={','window.qa={onIsland,insideFort,goalScore,MISSION_RESPAWN_MULTIPLIER,createMonster,updateMonsters,updateEnemyBolts,enemyBolts:()=>enemyBolts,startMission,mission:kind=>missions.find(m=>m.kind===kind),missions:()=>missions.map(m=>({...m,tokens:m.tokens.map(t=>({...t}))})),monsters:()=>monsters,magicArmor:()=>[...magicArmor],missionRaiders:()=>monsters.filter(m=>m.missionId==="village"),firstMonster:()=>monsters.find(m=>m.alive&&!m.missionId),updateMissions,updateCharge,drawMap,record:()=>bestTime,clock:value=>elapsed=value,charge:()=>chargeHold?{id:chargeHold.id,elapsed:chargeHold.elapsed,triggered:chargeHold.triggered,source:chargeHold.source.id}:null,landmarks:()=>landmarks.map(s=>({...s})),coastRadii:()=>coastRadii.slice(),');
 const storage=new Map(Object.entries(options.storage||{}));if(options.saved)storage.set('isla-brava-avatar',JSON.stringify(options.saved));
 vm.runInNewContext(testSource.replace('window.qa={','window.qa={enterJungle,jungleWalkable,nearJungleRiver,riverCenter,tributaryCenter,bridges:()=>jungleBridges,updatePoison,venomHit,poison:()=>({...poison}),ancestral:()=>[...ancestralArmor],campaignLevel:()=>level,completeAdventure:()=>{if(level===1){enterCave();hitBoss(99999);}enterCave();hitBoss(99999);},setGraphicsQuality,graphics:()=>graphicsQuality,weaponDamage,updateDemonicSword,demonicTime:()=>demonicSwordTime,demonicCooldown:()=>demonicSwordCooldown,updateImpactEffects,hitTarget,impacts:()=>impactEffects.map(effect=>({...effect})),effectMesh:()=>{const saved=dynamic;dynamic=[];drawImpactEffects();const mesh=dynamic;dynamic=saved;return mesh;},cameraState:()=>({distance:cameraDistance,yaw:cameraYaw,pitch:cameraPitch}),'),{window,document,console,botFrame:0,location:{hash:options.hash||''},matchMedia:()=>({matches:!!options.coarse}),localStorage:{getItem:key=>storage.get(key)??null,setItem:(key,value)=>storage.set(key,String(value))},innerWidth:1280,innerHeight:800,devicePixelRatio:options.dpr||1,requestAnimationFrame:fn=>raf=fn,setTimeout(){},Float32Array,Math,Error,Object});
 const fire=(target,n,data={})=>{const e={preventDefault(){},pointerId:1,clientX:56,clientY:56,button:0,detail:1,repeat:false,shiftKey:false,target:element('world'),...data};for(const f of target==='window'?(events.get(n)||[]):(element(target).events.get(n)||[]))f(e);};
 const key=(code,data={})=>fire('window','keydown',{code,...data});
 const frames=count=>{for(let i=0;i<count;i++){time+=1000/60;raf(time);}};
 return {qa:window.qa,element,document,fire,key,frames,storage};
}
let passed=0,failed=0;function test(name,fn){try{fn();passed++;console.log('OK '+name);}catch(e){failed++;console.error('FAIL '+name+': '+e.message);}}
test('Sword hits draw a slash and push a surviving enemy away from the player',()=>{
 const h=boot(),q=h.qa;q.start();q.mobs([[0,-2.5]]);const m=q.monsters()[0];Object.assign(m,{kind:'charger',health:42,maxHealth:42,windup:.5,chargeTime:.4});q.attack();assert.equal(m.health,18);assert.equal(q.impacts()[0].type,'slash');assert.equal(m.windup,0);assert.equal(m.chargeTime,0);const normalSize=q.effectMesh().length;assert(normalSize>200);q.updateImpactEffects(.12);assert(m.z<-2.9);q.render();
 const charged=boot(),c=charged.qa;c.start();c.mobs([[0,-2.5]]);Object.assign(c.monsters()[0],{health:120,maxHealth:120});c.attack(true);assert.equal(c.impacts().length,0);assert.equal(c.monsters()[0].health,120);c.attack();assert.equal(c.monsters()[0].health,83);assert.equal(c.impacts()[0].demonic,true);assert.equal(c.effectMesh().length,normalSize);
});
test('Blaster flames attach to the shot impact and follow the enemy position and rotation',()=>{
 const h=boot(),q=h.qa;q.avatar(1);q.start();q.mobs([[0,-10]]);const m=q.monsters()[0];Object.assign(m,{kind:'thrower',health:34,maxHealth:34});q.attack();assert.equal(q.impacts().length,0);for(let i=0;i<15;i++)q.updateWeapons(.04);assert.equal(m.health,16);const effect=q.impacts()[0];assert.equal(effect.type,'fire');assert(Math.hypot(effect.localX,effect.localZ)>.3);assert(effect.localY>.8&&effect.localY<1.5);assert(!m.recoil);m.x+=3;m.z+=2;m.yaw=Math.PI/2;const mesh=q.effectMesh();assert(Math.abs(mesh[0]-(m.x+effect.localZ+Math.sin(effect.seed)*.23))<.0001);assert(Math.abs(mesh[2]-(m.z-effect.localX+Math.cos(effect.seed)*.20))<.0001);assert(mesh.every(Number.isFinite));q.updateWeapons(1);assert.equal(m.health,16);q.render();
});
test('Hammer area hits push each affected enemy outward and surround them with electricity',()=>{
 const h=boot(),q=h.qa;q.avatar(2);q.start();q.mobs([[0,-2.5],[1,-2.7],[12,0]]);const mobs=q.monsters();for(const m of mobs)Object.assign(m,{health:100,maxHealth:100});q.attack();const impact=q.get().pending,distances=mobs.map(m=>Math.hypot(m.x-impact.x,m.z-impact.z));q.updateWeapons(.28);assert.equal(q.impacts().length,2);assert(q.impacts().every(e=>e.type==='electric'));for(let i=0;i<2;i++){assert.equal(mobs[i].health,68);assert(Math.hypot(mobs[i].x-impact.x,mobs[i].z-impact.z)>distances[i]+.6);}assert.equal(mobs[2].health,100);const mesh=q.effectMesh();assert(mesh.length>400&&mesh.every(Number.isFinite));q.render();
});
test('Enemy knockback respects fort walls and the island shore',()=>{
 const h=boot(),q=h.qa;q.start();const f=q.get().forts[0];q.mobs([[f.x-23.5,f.z]]);let m=q.monsters()[0];Object.assign(m,{health:100,maxHealth:100});q.hitTarget(m,1,{weapon:'sword',sourceX:f.x-26,sourceZ:f.z});q.updateImpactEffects(.3);assert(m.x<=f.x-23.2);const edge={x:0,z:0};q.moveBody(edge,500,0,.55);q.mobs([[edge.x,edge.z]]);m=q.monsters()[0];Object.assign(m,{health:100,maxHealth:100});q.hitTarget(m,1,{weapon:'hammer',sourceX:edge.x-2,sourceZ:edge.z,charged:true});q.updateImpactEffects(.3);assert(q.onIsland(m.x,m.z,.55));
});
test('Impact effects and recoil freeze on pause and clear when entering the cave',()=>{
 const h=boot(),q=h.qa;q.start();q.mobs([[0,-2.5]]);const m=q.monsters()[0];Object.assign(m,{health:100,maxHealth:100});q.attack();const before=q.impacts()[0],z=m.z,time=m.recoil.time,mesh=q.effectMesh();q.pause();q.update(2);q.updateWeapons(2);q.updateImpactEffects(2);assert.equal(m.z,z);assert.equal(m.recoil.time,time);assert.equal(q.impacts()[0].life,before.life);assert.deepEqual(q.effectMesh(),mesh);q.resume();q.updateImpactEffects(.04);assert(m.z<z);q.enterCave();assert.equal(q.impacts().length,0);assert.equal(m.recoil,null);q.render();
});
test('Lethal hits keep a short defeat animation and respawning clears every impact',()=>{
 const h=boot(),q=h.qa;q.start();q.mobs([[0,-2.5]]);const m=q.monsters()[0];q.attack();assert.equal(m.alive,false);assert(m.defeatVisual>0);assert.equal(q.get().score,10);q.render();m.respawnTimer=.01;q.set({x:30,z:30});q.updateMonsters(.02);assert.equal(m.alive,true);assert.equal(m.defeatVisual,0);assert.equal(m.recoil,null);assert.equal(q.impacts().length,0);assert.equal(q.get().experience,10);
});
test('The golem receives impact effects with reduced recoil and keeps its announced attack',()=>{
 const h=boot(),q=h.qa;q.start();q.enterCave();q.bossSet({x:0,z:0,action:'slam',timer:1});const boss=q.get().boss;q.set({x:0,z:4,yaw:Math.PI});q.attack();q.updateImpactEffects(.21);const after=q.get().boss;assert.equal(after.action,'slam');assert.equal(after.timer,1);assert.equal(after.health,936);assert(Math.abs(after.z-boss.z)>.1&&Math.abs(after.z-boss.z)<.35);assert(q.effectMesh().every(Number.isFinite));q.render();
});
test('Camera avoids the spawn arch and remains finite when jumping below it',()=>{const h=boot(),q=h.qa;q.start();q.render();const eye=q.get().camera;assert(q.cameraSolids.every(b=>{const t=q.segmentBox([0,1.4,0],eye,b);return t===null||t<.00001||t>=1;}),'Camera view crosses scenery');q.set({x:0,z:3.5,y:1.5});q.render();});
test('A fort corner blocks enemy damage',()=>{const h=boot(),q=h.qa;q.start();const f=q.get().forts[0],x=f.x+3.5,z=f.z+20;q.set({x,z,health:100,invulnerable:0});q.mobs([[f.x+4.4,f.z+21.4]]);assert(q.blocked(x,z,f.x+4.4,f.z+21.4));q.update(1/60);assert.equal(q.get().health,100);});
test('Monster hits jolt and push the avatar away without crossing walls or shore',()=>{const h=boot(),q=h.qa;q.start();q.mobs([[-1.5,0]]);q.set({x:0,z:0,health:100,invulnerable:0});q.update(1/60);assert.equal(q.get().health,88);assert(q.get().player.hitJolt>0);q.mobs([]);for(let i=0;i<12;i++)q.update(1/60);assert(q.get().player.x>.65&&q.get().player.x<1.4);const f=q.get().forts[0];q.set({x:f.x-23.25,z:f.z,y:0,vy:0,invulnerable:0});q.damage(12,{x:f.x-24.5,z:f.z});for(let i=0;i<12;i++)q.update(1/60);assert(q.get().player.x<=f.x-23.2);const edge={x:0,z:0};q.moveBody(edge,500,0,.42);q.set({x:edge.x,z:edge.z,y:0,vy:0,invulnerable:0});q.damage(12,{x:edge.x-1,z:edge.z});for(let i=0;i<12;i++)q.update(1/60);assert(q.onIsland(q.get().player.x,q.get().player.z,.42));});
test('The island spawns pursuers, chargers and throwers with distinct silhouettes',()=>{const h=boot(),q=h.qa;q.start();const types=new Set(q.monsters().map(m=>m.kind));assert.deepEqual([...types].sort(),['charger','chaser','thrower']);assert(q.monsters().every(m=>m.alive&&m.color.every(Number.isFinite)));q.render();});
test('Chargers warn, commit to a direction, and can be dodged',()=>{const h=boot(),q=h.qa;q.start();q.mobs([[0,-7]]);let m=q.monsters()[0];Object.assign(m,{kind:'charger',windup:0,chargeTime:0,chargeCooldown:0,chargeX:0,chargeZ:0});q.set({x:0,z:0,y:0,health:100,invulnerable:0});q.updateMonsters(.04);assert(m.windup>.6);assert.equal(m.z,-7);q.updateMonsters(.7);assert(m.chargeTime>0);q.set({x:4,z:0});q.updateMonsters(.3);q.updateMonsters(.35);assert.equal(q.get().health,100);q.mobs([[0,-7]]);m=q.monsters()[0];Object.assign(m,{kind:'charger',windup:0,chargeTime:0,chargeCooldown:0,chargeX:0,chargeZ:0});q.set({x:0,z:0,health:100,invulnerable:0});q.updateMonsters(.04);q.updateMonsters(.7);q.updateMonsters(.5);assert.equal(q.get().health,84);});
test('Thrower projectiles can hit, be dodged, and do not cross fort walls',()=>{const h=boot(),q=h.qa;q.start();q.mobs([[0,-10]]);const m=q.monsters()[0];Object.assign(m,{kind:'thrower',attack:0,speed:0});q.set({x:0,z:0,y:0,health:100,invulnerable:0});q.updateMonsters(.04);assert.equal(q.enemyBolts().length,1);q.mobs([]);for(let i=0;i<30;i++)q.updateEnemyBolts(.04);assert.equal(q.get().health,90);assert.equal(q.enemyBolts().length,0);q.mobs([[0,-10]]);Object.assign(q.monsters()[0],{kind:'thrower',attack:0,speed:0});q.set({x:0,z:0,y:1.2,health:100,invulnerable:0});q.updateMonsters(.04);q.mobs([]);for(let i=0;i<70;i++)q.updateEnemyBolts(.04);assert.equal(q.get().health,100);assert.equal(q.enemyBolts().length,0);const f=q.get().forts[0];q.mobs([[f.x-29,f.z]]);Object.assign(q.monsters()[0],{kind:'thrower',attack:0,speed:0});q.set({x:f.x-17,z:f.z,y:0});assert(q.blocked(f.x-29,f.z,f.x-17,f.z));q.updateMonsters(.04);assert.equal(q.enemyBolts().length,0);});
test('Enemy shots freeze on pause and clear before the boss fight',()=>{const h=boot(),q=h.qa;q.start();q.mobs([[0,-10]]);Object.assign(q.monsters()[0],{kind:'thrower',attack:0,speed:0});q.set({x:0,z:0,y:0});q.updateMonsters(.04);assert.equal(q.enemyBolts().length,1);q.pause();const before={...q.enemyBolts()[0]};q.update(1);assert.equal(q.enemyBolts()[0].z,before.z);q.resume();q.enterCave();assert.equal(q.enemyBolts().length,0);});
test('Healing is collected before a same-frame lethal hit',()=>{const h=boot(),q=h.qa;q.start();q.render();const k=q.get().kits[0];q.set({x:k.x,z:k.z,health:12,invulnerable:0});q.mobs([[k.x+1.5,k.z]]);q.update(1/60);assert.equal(q.get().state,'playing');assert.equal(q.get().health,30);});
test('Attack button works with keyboard activation',()=>{const h=boot(),q=h.qa;q.start();q.render();q.mobs([[0,-2]]);h.fire('attack','click',{detail:0});assert.equal(q.get().score,10);});
test('An unrelated finger cannot release the joystick',()=>{const h=boot({coarse:true}),q=h.qa;q.start();h.fire('joystick','pointerdown',{pointerId:10,clientX:87,clientY:56,pointerType:'touch'});assert(q.get().joy.x>0);h.fire('joystick','pointerup',{pointerId:20,pointerType:'touch'});assert(q.get().joy.x>0);h.fire('joystick','pointerup',{pointerId:10});assert.equal(q.get().joy.x,0);});
test('A joystick scaled to 80 percent keeps its full movement range',()=>{const h=boot({coarse:true}),q=h.qa;q.start(),stick=h.element('stick'),joystick=h.element('joystick');joystick.offsetWidth=112;joystick.getBoundingClientRect=()=>({left:20,top:20,width:89.6,height:89.6});h.fire('joystick','pointerdown',{pointerId:10,pointerType:'touch',clientX:92,clientY:64.8});assert(Math.abs(q.get().joy.x-1)<.001);assert.equal(q.get().joy.y,0);assert.match(stick.style.transform,/translate\(34(?:\.0+)?px,0px\)/);h.fire('joystick','pointerup',{pointerId:10,pointerType:'touch'});assert.equal(q.get().joy.x,0);});
test('Pause clears captured touch movement',()=>{const h=boot({coarse:true}),q=h.qa;q.start();h.fire('joystick','pointerdown',{pointerId:10,clientX:87,clientY:56,pointerType:'touch'});q.pause();assert.equal(q.get().joyId,null);q.resume();h.fire('joystick','pointermove',{pointerId:10,clientX:90,clientY:56});assert.equal(q.get().joy.x,0);});
test('An unrelated pointer cannot cancel camera dragging',()=>{const h=boot(),q=h.qa;q.start();h.fire('world','pointerdown',{button:2,pointerId:10});h.fire('world','pointerup',{pointerId:20});assert.equal(q.get().drag.id,10);h.fire('world','pointerup',{pointerId:10});assert.equal(q.get().drag,null);});
test('Two touches pinch the camera without rotating it, then one touch resumes dragging',()=>{const h=boot({coarse:true}),q=h.qa;q.start();h.fire('world','pointerdown',{pointerType:'touch',pointerId:10,clientX:300,clientY:300});h.fire('world','pointerdown',{pointerType:'touch',pointerId:11,clientX:400,clientY:300});const before=q.cameraState();h.fire('world','pointermove',{pointerType:'touch',pointerId:11,clientX:450,clientY:300});assert(Math.abs(q.cameraState().distance-11*100/150)<.001);assert.equal(q.cameraState().yaw,before.yaw);assert.equal(q.cameraState().pitch,before.pitch);h.fire('world','pointerup',{pointerType:'touch',pointerId:99});assert.equal(q.get().drag,null);h.fire('world','pointermove',{pointerType:'touch',pointerId:11,clientX:350,clientY:300});assert.equal(q.cameraState().distance,19);h.fire('world','pointerup',{pointerType:'touch',pointerId:11});assert.equal(q.get().drag.id,10);h.fire('world','pointermove',{pointerType:'touch',pointerId:10,clientX:320,clientY:300});assert.notEqual(q.cameraState().yaw,before.yaw);q.pause();assert.equal(q.get().drag,null);q.resume();const yaw=q.cameraState().yaw;h.fire('world','pointermove',{pointerType:'touch',pointerId:10,clientX:360,clientY:300});assert.equal(q.cameraState().yaw,yaw);});
test('Holding Escape does not repeatedly toggle pause',()=>{const h=boot(),q=h.qa;q.start();h.key('Escape');assert.equal(q.get().state,'paused');h.key('Escape',{repeat:true});assert.equal(q.get().state,'paused');});
test('Touch input on a hybrid device enables touch controls',()=>{const h=boot(),q=h.qa;q.start();h.fire('window','pointerdown',{pointerType:'touch'});assert.equal(h.element('touch-controls').hidden,false);assert(h.document.body.classList.contains('touch-mode'));});
test('WebGL context loss stops the animation loop',()=>{const h=boot(),q=h.qa;q.start();h.fire('world','webglcontextlost');assert(q.get().lost);assert.equal(q.get().state,'paused');});
test('Focus enters pause and returns to the game',()=>{const h=boot(),q=h.qa;q.start();q.pause();assert.equal(h.document.activeElement.id,'resume');q.resume();assert.equal(h.document.activeElement.id,'world');});
test('The 500 m map has reachable fort gates and the coast blocks travel into water',()=>{const h=boot(),q=h.qa;q.start();assert.equal(q.mapPosition(-250),0);assert.equal(q.mapPosition(250),200);assert.equal(h.element('map-scale').textContent,'500 × 500 M');for(const f of q.get().forts){const p={x:f.x,z:f.z+f.gateSide*30};for(let i=0;i<180;i++)q.moveBody(p,0,-f.gateSide*.15,.42);assert(Math.abs(p.z-(f.z+f.gateSide*3))<.01);const wall={x:f.x-26,z:f.z};for(let i=0;i<70;i++)q.moveBody(wall,.1,0,.42);assert(wall.x<=f.x-23.2);}for(const angle of [0,.7,1.4,2.1,3,4,5]){const p={x:0,z:0};for(let i=0;i<300;i++)q.moveBody(p,Math.cos(angle),Math.sin(angle),.42);assert(Math.hypot(p.x,p.z)<220);assert(Math.abs(p.x)<250&&Math.abs(p.z)<250);}});
test('A new game regenerates every fort and landmark on dry land',()=>{const h=boot(),q=h.qa;let previous=null;for(let run=0;run<5;run++){q.start();const forts=q.get().forts.map(f=>({id:f.id,x:f.x,z:f.z,gateSide:f.gateSide})),sites=q.landmarks();assert.equal(sites.length,4);assert.deepEqual(sites.map(s=>s.kind).sort(),['lake','ruins','tower','village']);for(const s of sites)assert(q.onIsland(s.x,s.z,s.radius+5));for(const f of forts){assert(q.onIsland(f.x,f.z,35));const vendors=q.get().npcs.filter(n=>n.fort===f.id);assert.equal(vendors.length,2);assert(vendors.every(n=>Math.abs(n.x-f.x)===9&&n.z===f.z+f.gateSide*3));}assert(q.coastRadii().every(r=>r>160&&r<220));assert(q.get().kits.every(k=>q.onIsland(k.x,k.z,2)));if(previous){assert(forts.every((f,i)=>Math.hypot(f.x-previous.forts[i].x,f.z-previous.forts[i].z)>10));assert(sites.every((s,i)=>Math.hypot(s.x-previous.sites[i].x,s.z-previous.sites[i].z)>5));}previous={forts,sites};}});
test('Defeated island monsters respawn away from the player for a 300-point run',()=>{const h=boot(),q=h.qa;q.start();assert.equal(q.goalScore(),300);assert.match(html,/role="progressbar"[^>]*aria-valuemax="300"/);const m=q.firstMonster();q.hitMonster(m);assert.equal(q.get().score,10);assert.equal(m.alive,false);assert(m.respawnTimer>0);q.set({x:m.homeX+25,z:m.homeZ+25});m.respawnTimer=.01;q.update(.02);assert.equal(m.alive,true);assert.equal(q.get().score,10);});
test('Initial monsters and later respawns stay outside both forts',()=>{const h=boot(),q=h.qa;q.start();assert(q.monsters().every(m=>!q.insideFort(m.x,m.z,3)));const f=q.get().forts[0];q.mobs([[f.x,f.z]]);const m=q.firstMonster();q.hitMonster(m);m.respawnTimer=.01;q.set({x:0,z:0});q.update(.02);assert.equal(m.alive,true);assert.equal(q.insideFort(m.x,m.z,3),false);});
test('Starting a mission adds three nearby enemies and quadruples their respawn rate',()=>{const h=boot(),q=h.qa;q.start();assert.equal(q.MISSION_RESPAWN_MULTIPLIER,4);const baseline=q.monsters().length,m=q.firstMonster();q.hitMonster(m);assert(m.respawnTimer>=9&&m.respawnTimer<=14);const mission=q.mission('ruins');q.set({x:mission.x,z:mission.z,y:0});h.key('KeyF');assert.equal(mission.status,'active');assert.equal(q.monsters().length,baseline+3);assert(m.respawnTimer>=9/4&&m.respawnTimer<=14/4);const extras=q.monsters().slice(-3);assert(extras.every(e=>e.alive&&!q.insideFort(e.x,e.z,3)&&Math.hypot(e.x-mission.x,e.z-mission.z)>=9&&Math.hypot(e.x-mission.x,e.z-mission.z)<=33));const second=q.monsters().find(e=>e.alive&&!extras.includes(e));q.hitMonster(second);assert(second.respawnTimer>=9/4&&second.respawnTimer<=14/4);m.respawnTimer=.01;q.update(.02);assert.equal(m.alive,true);assert.equal(q.insideFort(m.x,m.z,3),false);assert(Math.hypot(m.x-mission.x,m.z-mission.z)<=33);});
test('Four structure missions each give one distinct magical armor part',()=>{const h=boot(),q=h.qa;q.start();const list=q.missions();assert.equal(list.length,4);assert.deepEqual(list.map(m=>m.kind).sort(),['lake','ruins','tower','village']);assert(list.every(m=>m.status==='available'&&q.onIsland(m.x,m.z,2)));for(const kind of ['lake','ruins','tower','village']){const m=q.mission(kind),before=q.magicArmor().length;q.set({x:m.x,z:m.z,y:0});if(kind==='lake')h.key('KeyF');else h.fire('interact','click');assert.equal(m.status,'active');assert.equal(q.magicArmor().length,before);if(kind==='lake'||kind==='ruins'){assert.equal(m.tokens.length,3);for(const token of m.tokens){q.set({x:token.x,z:token.z,y:0});q.updateMissions(.02);}}else if(kind==='tower'){q.updateMissions(8.01);}else{const raiders=q.missionRaiders();assert.equal(raiders.length,3);for(const raider of raiders)q.hitMonster(raider);}assert.equal(m.status,'done');assert.equal(q.magicArmor().length,before+1);assert.equal(q.get().armor.length,before+1);assert.equal(h.element('magic-count').textContent,'✦ '+(before+1));assert.equal(q.missionRaiders().filter(r=>r.alive).length,0);q.startMission(m);assert.equal(q.magicArmor().length,before+1);}assert.equal(new Set(q.magicArmor()).size,4);assert.equal(q.get().score,30);assert.equal(q.get().region,'island');q.start();assert.equal(q.magicArmor().length,0);assert(q.missions().every(m=>m.status==='available'));});
test('The minimap highlights active missions and shows the nearest objective distance',()=>{const h=boot(),q=h.qa;q.start();q.drawMap();assert.equal(h.element('map-objective').hidden,true);const mission=q.mission('ruins');q.startMission(mission);q.drawMap();assert.equal(h.element('map-objective').hidden,false);assert(h.element('map-objective').textContent.includes('Ruinas Antiguas'));assert.match(h.element('map-objective').textContent,/\d+ m/);q.set({x:mission.x,z:mission.z});q.drawMap();assert(h.element('map-objective').textContent.includes('0 m'));mission.progress=mission.goal;q.updateMissions(.01);q.drawMap();assert.equal(h.element('map-objective').hidden,true);q.enterCave();assert.equal(h.element('map-objective').hidden,true);});
test('Magical armor upgrades purchased armor visually and doubles its protection',()=>{const h=boot(),q=h.qa;q.start();q.xp(50);const vendor=q.get().npcs.find(n=>n.kind==='armor');q.set({x:vendor.x,z:vendor.z+2});q.openShop();for(const id of ['helmet','chest','shoulders','gloves','boots'])assert(q.buyArmor(id));q.closeShop();const normal=q.gearMesh();q.set({health:100,invulnerable:0});q.damage(20);assert.equal(q.get().health,90);const tower=q.mission('tower');q.set({x:tower.x,z:tower.z,y:0,health:100,invulnerable:0});h.key('KeyF');q.updateMissions(8.01);assert.equal(q.magicArmor().length,1);assert.equal(q.get().armor.length,5);assert(q.gearMesh().length>normal.length,'Magical trim and crystals must add geometry');q.set({health:100,invulnerable:0});q.damage(20);assert.equal(q.get().health,92);q.set({x:vendor.x,z:vendor.z+2});q.openShop();const magic=q.magicArmor()[0];assert.equal(q.buyArmor(magic),false);assert.equal(h.element('buy-'+magic).querySelector('.price').textContent,'✦ MÁGICA');});
test('Healing cap, full health preservation, respawn and pause',()=>{const h=boot(),q=h.qa;q.start();q.render();q.mobs([]);const k=q.get().kits[0];q.set({x:k.x,z:k.z,health:100});q.updateMedkits(.02);assert.equal(q.get().kits[0].cooldown,0);q.set({health:89});q.updateMedkits(.02);assert.equal(q.get().health,100);assert.equal(q.get().kits[0].cooldown,20);q.pause();q.updateMedkits(50);assert.equal(q.get().kits[0].cooldown,20);q.resume();q.set({x:0,z:0});q.updateMedkits(20);assert.equal(q.get().kits[0].cooldown,0);});
test('All three weapon types, cooldowns, projectiles and area impact',()=>{for(let i=0;i<3;i++){const h=boot(),q=h.qa;q.avatar(i);q.start();q.render();q.mobs(i===1?[[0,-12]]:[[0,-2.5],[1,-2.7],[-1,-2.6]]);q.attack();if(i===0)assert.equal(q.get().score,10);else{assert.equal(q.get().score,0);for(let j=0;j<16;j++)q.updateWeapons(.04);assert.equal(q.get().score,i===1?10:30);}const score=q.get().score;q.attack();assert.equal(q.get().score,score);}});
test('Sword taps attack; holding three seconds transforms once and requires release before striking',()=>{
 const h=boot(),q=h.qa;q.avatar(0);q.start();q.mobs([[0,-2]]);h.fire('world','pointerdown',{pointerType:'mouse',pointerId:7});q.updateCharge(2.99);assert.equal(q.get().score,0);h.fire('world','pointerup',{pointerType:'mouse',pointerId:7});assert.equal(q.get().score,10);assert.equal(q.charge(),null);
 q.mobs([]);q.update(.5);q.mobs([[0,-2]]);Object.assign(q.monsters()[0],{health:100,maxHealth:100});h.fire('attack','pointerdown',{pointerType:'touch',pointerId:11});q.updateCharge(2.99);assert.equal(q.demonicTime(),0);q.updateCharge(.01);assert.equal(q.demonicTime(),15);assert.equal(q.monsters()[0].health,100);assert(q.charge().triggered);assert.equal(h.element('charge-meter').getAttribute('aria-valuenow'),'3.00');q.updateDemonicSword(1);q.updateCharge(10);q.attack();assert.equal(q.demonicTime(),14);assert.equal(q.monsters()[0].health,100);
 h.fire('attack','pointerup',{pointerType:'touch',pointerId:12});assert(q.charge());h.fire('attack','pointerup',{pointerType:'touch',pointerId:11});assert.equal(q.charge(),null);assert.equal(q.monsters()[0].health,100);h.fire('attack','pointerdown',{pointerType:'touch',pointerId:13});h.fire('attack','pointerup',{pointerType:'touch',pointerId:13});assert.equal(q.monsters()[0].health,63);
});
test('Pause and cancellation discard a partial charge without an attack',()=>{const h=boot(),q=h.qa;q.start();q.mobs([[0,-2]]);h.fire('attack','pointerdown',{pointerType:'touch',pointerId:3});q.updateCharge(2);h.fire('attack','pointercancel',{pointerType:'touch',pointerId:3});assert.equal(q.charge(),null);assert.equal(q.get().score,0);h.fire('attack','pointerdown',{pointerType:'touch',pointerId:4});q.updateCharge(2);q.pause();assert.equal(q.charge(),null);q.resume();q.updateCharge(4);assert.equal(q.get().score,0);});
test('The main game loop reaches the three-second charge threshold',()=>{const h=boot(),q=h.qa;q.avatar(1);q.start();q.mobs([]);h.fire('attack','pointerdown',{pointerType:'touch',pointerId:5});q.update(2.99);assert.equal(q.get().bolts.length,0);q.update(.01);assert.equal(q.get().bolts.length,1);assert(q.get().bolts[0].charged);q.update(4);assert(q.charge().triggered);assert.equal(q.get().bolts.length,0);h.fire('attack','pointerup',{pointerType:'touch',pointerId:5});assert.equal(q.charge(),null);});
test('Charged blaster deal more damage to tough monsters and the boss',()=>{for(const avatar of [1]){const h=boot(),q=h.qa;q.avatar(avatar);q.start();q.render();q.mobs([[0,avatar===0?-2:-12]]);const m=q.monsters()[0];Object.assign(m,{kind:avatar===0?'charger':'thrower',maxHealth:avatar===0?42:34,health:avatar===0?42:34});q.attack();for(let i=0;i<18;i++)q.updateWeapons(.04);assert.equal(q.get().score,0);assert(m.health>0);q.mobs([[0,avatar===0?-2:-12]]);const tough=q.monsters()[0];Object.assign(tough,{kind:avatar===0?'charger':'thrower',maxHealth:avatar===0?42:34,health:avatar===0?42:34});q.update(.6);h.fire('attack','pointerdown',{pointerType:'touch',pointerId:8});q.updateCharge(3);for(let i=0;i<18;i++)q.updateWeapons(.04);assert.equal(q.get().score,10);h.fire('attack','pointerup',{pointerType:'touch',pointerId:8});q.enterCave();const b=q.get().boss;q.set({x:b.x,z:b.z+4,y:0,yaw:Math.PI});h.fire('world','pointerdown',{pointerType:'mouse',pointerId:9});q.updateCharge(3);for(let i=0;i<18;i++)q.updateWeapons(.04);assert.equal(q.get().boss.health,960-(avatar===0?60:54));h.fire('world','pointerup',{pointerType:'mouse',pointerId:9});}});
test('Charged hammer reaches a wider area and more targets',()=>{const h=boot(),q=h.qa;q.avatar(2);q.start();q.render();q.mobs([[4,-3.2]]);q.attack();q.updateWeapons(.3);assert.equal(q.get().score,0);q.update(.9);h.fire('attack','pointerdown',{pointerType:'touch',pointerId:6});q.updateCharge(3);assert(q.get().pending.radius>=6);assert(q.get().pending.targets>3);q.updateWeapons(.3);assert.equal(q.get().score,10);h.fire('attack','pointerup',{pointerType:'touch',pointerId:6});});
test('Fort walls block blaster shots',()=>{const h=boot(),q=h.qa;q.avatar(1);q.start();const f=q.get().forts[0];q.set({x:f.x+10,z:f.z+16,yaw:0});q.mobs([[f.x+10,f.z+25]]);q.render();q.attack();for(let i=0;i<20;i++)q.updateWeapons(.04);assert.equal(q.get().score,0);assert.equal(q.get().bolts.length,0);});
test('Pause freezes movement, damage, cooldowns and projectiles',()=>{const h=boot(),q=h.qa;q.avatar(1);q.start();q.render();q.mobs([[0,-12]]);q.attack();q.pause();const before=q.get();q.update(1);const after=q.get();assert.equal(after.elapsed,before.elapsed);assert.equal(after.health,before.health);assert.equal(after.cooldown,before.cooldown);assert.equal(after.bolts[0].z,before.bolts[0].z);});
test('Every avatar can score, reach the cave at 300, clear both islands and bosses, and replay',()=>{for(let avatar=0;avatar<3;avatar++){const h=boot(),q=h.qa;q.avatar(avatar);q.start();q.render();for(let i=0;i<5400&&q.get().score<100&&q.get().state==='playing';i++)q.ai();assert.equal(q.get().score,100,'Avatar '+avatar+' cannot defeat ten monsters');assert.equal(q.get().region,'island');for(let i=0;i<20;i++)q.defeat();assert.equal(q.get().region,'cave');assert.equal(q.get().score,300);for(let i=0;i<60&&q.get().state==='playing';i++)q.hitBoss();assert.equal(q.campaignLevel(),2);assert.equal(q.get().score,0);for(let i=0;i<35;i++)q.defeat();assert.equal(q.get().boss.health,1200);for(let i=0;i<80&&q.get().state==='playing';i++)q.hitBoss();assert.equal(q.get().state,'won','Avatar '+avatar+' cannot finish both levels');assert.equal(q.get().boss.alive,false);q.attack();assert.equal(q.get().score,350);q.start();assert.equal(q.get().region,'island');assert.equal(q.get().boss,null);assert.equal(q.get().score,0);assert.equal(q.get().health,100);assert.equal(q.get().bolts.length,0);assert.equal(q.get().pending,null);assert(q.get().kits.every(k=>k.cooldown===0));}});

test('Both forts have two reachable NPCs and F opens their shops',()=>{const h=boot(),q=h.qa;q.start();assert.equal(q.get().npcs.length,4);for(const f of q.get().forts){const vendors=q.get().npcs.filter(n=>n.fort===f.id);assert.equal(vendors.length,2);assert.deepEqual(vendors.map(n=>n.kind).sort(),['armor','forge']);for(const n of vendors){q.set({x:n.x,z:n.z+f.gateSide*2,y:0});assert(q.npcAccessible(n));h.key('KeyF');assert.equal(q.get().state,'shop');assert.equal(q.get().shop.id,n.id);assert.equal(h.document.activeElement.id,'close-shop');h.key('Escape');assert.equal(q.get().state,'playing');}}q.set({x:0,z:0});q.openShop();assert.equal(q.get().state,'playing');});
test('Experience is awarded once per monster and spending preserves victory points',()=>{const h=boot(),q=h.qa;q.start();q.render();q.mobs([[0,-2]]);q.attack();assert.equal(q.get().score,10);assert.equal(q.get().experience,10);q.attack();assert.equal(q.get().experience,10);const n=q.get().npcs.find(n=>n.kind==='armor');q.set({x:n.x,z:n.z+2});q.openShop();assert(q.buyArmor('helmet'));assert.equal(q.get().experience,0);assert.equal(q.get().score,10);assert.equal(q.get().state,'shop');});
test('Five armor pieces cost 10 XP each, change geometry and reduce damage',()=>{const h=boot(),q=h.qa;q.start();q.xp(50);const n=q.get().npcs.find(n=>n.kind==='armor');q.set({x:n.x,z:n.z+2});q.openShop();let length=q.gearMesh().length;for(const [i,id] of ['helmet','chest','shoulders','gloves','boots'].entries()){assert(q.buyArmor(id));assert.equal(q.get().experience,40-i*10);assert.equal(q.get().armor.length,i+1);const mesh=q.gearMesh();assert(mesh.length>length,'The new armor part has no visible geometry');assert(mesh.every(Number.isFinite));length=mesh.length;assert.equal(q.buyArmor(id),false);}assert.equal(q.buyArmor('unknown'),false);assert.equal(q.get().experience,0);q.closeShop();q.set({health:100,invulnerable:0});q.damage();assert.equal(q.get().health,98);q.start();assert.equal(q.get().armor.length,0);assert.equal(q.get().experience,0);});
test('Armor inventory is shared by the two forts',()=>{const h=boot(),q=h.qa;q.start();q.xp(20);const vendors=q.get().npcs.filter(n=>n.kind==='armor');q.set({x:vendors[0].x,z:vendors[0].z+2});q.openShop();q.buyArmor('chest');q.closeShop();q.set({x:vendors[1].x,z:vendors[1].z-2});q.openShop();assert.equal(q.buyArmor('chest'),false);assert(q.buyArmor('boots'));assert.equal(q.get().experience,0);assert.equal(q.get().armor.length,2);});
test('Weapon upgrades improve all three weapons and stop at level three',()=>{for(let avatar=0;avatar<3;avatar++){const h=boot(),q=h.qa;q.avatar(avatar);q.start();q.xp(40);const n=q.get().npcs.find(n=>n.kind==='forge');q.set({x:n.x,z:n.z+2});q.openShop();const base=q.weaponFor(),mesh=q.gearMesh().length;for(let level=1;level<=3;level++){assert(q.upgradeWeapon());assert.equal(q.get().weaponLevel,level);assert.equal(q.get().experience,40-level*10);assert(q.weaponFor().range>base.range);assert(q.weaponFor().cooldown<base.cooldown);assert(q.gearMesh().length>mesh);}assert.equal(q.upgradeWeapon(),false);assert.equal(q.get().experience,10);assert.equal(q.buyArmor('helmet'),false);q.start();assert.equal(q.get().weaponLevel,0);assert.equal(q.weaponFor().range,base.range);}});
test('Upgraded hammer can hit more enemies',()=>{const h=boot(),q=h.qa;q.avatar(2);q.start();q.xp(30);const n=q.get().npcs.find(n=>n.kind==='forge');q.set({x:n.x,z:n.z+2});q.openShop();for(let i=0;i<3;i++)q.upgradeWeapon();q.closeShop();q.set({x:0,z:0,y:0,yaw:Math.PI});q.mobs([[0,-2.5],[1,-2.7],[-1,-2.6],[1.5,-3.5],[-1.5,-3.5]]);q.render();q.attack();for(let i=0;i<10;i++)q.updateWeapons(.04);assert.equal(q.get().score,50);});
test('Shops reject insufficient XP and freeze combat and time',()=>{const h=boot(),q=h.qa;q.start();const n=q.get().npcs.find(n=>n.kind==='armor');q.set({x:n.x,z:n.z+2,health:50,invulnerable:0});q.mobs([[n.x+1,n.z+2]]);q.openShop();q.resume();assert.equal(q.get().state,'shop');const before=q.get();assert.equal(q.buyArmor('boots'),false);assert.equal(q.upgradeWeapon(),false);h.frames(90);const after=q.get();assert.equal(after.experience,0);assert.equal(after.armor.length,0);assert.equal(after.health,before.health);assert.equal(after.elapsed,before.elapsed);assert.equal(after.worldTime,before.worldTime);q.xp(10);q.set({x:0,z:0});assert.equal(q.buyArmor('helmet'),false);assert.equal(q.get().experience,10);});

test('The thirtieth monster teleports to the cave and preserves purchased equipment',()=>{const h=boot(),q=h.qa;q.start();assert.equal(q.get().goalScore,300);assert.equal(h.element('score-goal').textContent,300);assert.equal(h.element('score-track').getAttribute('aria-valuemax'),'300');q.xp(80);const forge=q.get().npcs.find(n=>n.kind==='forge');q.set({x:forge.x,z:forge.z+2});q.openShop();for(let i=0;i<3;i++)q.upgradeWeapon();q.closeShop();const armorer=q.get().npcs.find(n=>n.kind==='armor');q.set({x:armorer.x,z:armorer.z+2});q.openShop();q.buyArmor('helmet');q.buyArmor('boots');q.closeShop();for(let i=0;i<29;i++)q.defeat();assert.equal(q.get().region,'island');assert.equal(q.get().score,290);assert(Math.abs(parseFloat(h.element('score-fill').style.width)-290/300*100)<.001);const before=q.get();q.set({health:13});q.defeat();const after=q.get();assert.equal(after.region,'cave');assert.equal(after.state,'playing');assert.equal(after.score,300);assert.equal(h.element('score-fill').style.width,'100%');assert.match(h.element('arrival-text').textContent,/300 puntos/);assert.equal(after.experience,before.experience+10);assert.equal(after.weaponLevel,3);assert.equal(after.armor.length,2);assert.equal(after.health,100);assert.equal(after.boss.health,960);assert.equal(after.boss.maxHealth,960);assert.equal(h.element('boss-health').textContent,'960 / 960');assert.equal(after.kits.length,4);assert.equal(after.player.z,15);assert.equal(h.element('result').hidden,true);q.bossSet({health:180});q.enterCave();assert.equal(q.get().boss.health,180);q.render();});
test('A hammer transition does not kill island enemies after teleporting',()=>{const h=boot(),q=h.qa;q.avatar(2);q.start();for(let i=0;i<29;i++)q.defeat();q.set({x:0,z:0,y:0,yaw:Math.PI});q.mobs([[0,-2.5],[1,-2.7],[-1,-2.6]]);q.render();q.attack();q.updateWeapons(.3);assert.equal(q.get().region,'cave');assert.equal(q.get().experience,300);assert.equal(q.get().boss.health,960);assert.equal(q.get().pending,null);assert.equal(q.get().bolts.length,0);});
test('Every weapon damages the boss without winning prematurely',()=>{for(let avatar=0;avatar<3;avatar++){const h=boot(),q=h.qa;q.avatar(avatar);q.start();q.enterCave();const b=q.get().boss;q.set({x:b.x,z:b.z+4,y:0,yaw:Math.PI});q.render();q.attack();for(let i=0;i<20;i++)q.updateWeapons(.03);assert(q.get().boss.health<960,'Avatar '+avatar+' cannot damage the boss');assert(q.get().boss.health>0);assert.equal(q.get().state,'playing');}});
test('The boss telegraphs the 78-damage slam and jumping avoids it',()=>{const h=boot(),q=h.qa;q.start();q.enterCave();q.bossSet({x:0,z:0,action:'slam',timer:.1,cooldown:10});q.set({x:0,z:5,health:100,invulnerable:0,y:0});q.updateBoss(.04);assert.equal(q.get().health,100);q.updateBoss(.07);assert.equal(q.get().health,22);q.set({health:100,invulnerable:0,y:1.2});q.bossSet({action:'slam',timer:.01});q.updateBoss(.02);assert.equal(q.get().health,100);q.render();});
test('Moving away from the 66-damage marked rock avoids damage',()=>{for(const dodge of [false,true]){const h=boot(),q=h.qa;q.start();q.enterCave();q.set({x:0,z:10,health:100,invulnerable:0});q.bossSet({action:'rock',timer:.2,cooldown:10,lockX:0,lockZ:10});for(let i=0;i<4;i++)q.updateBoss(.04);assert.equal(q.get().health,100);if(dodge)q.set({x:10,z:10});for(let i=0;i<25;i++)q.updateBoss(.04);assert.equal(q.get().health,dodge?100:34);q.render();}});
test('The second phase sends a 54-damage shockwave that can be jumped',()=>{for(const jumping of [false,true]){const h=boot(),q=h.qa;q.start();q.enterCave();q.set({x:0,z:10,health:100,invulnerable:0,y:jumping?1.2:0});q.bossSet({x:0,z:0,health:480,action:'slam',timer:.01,cooldown:10});q.updateBoss(.02);assert.equal(q.get().hazards.length,1);for(let i=0;i<30;i++)q.updateBoss(.04);assert.equal(q.get().health,jumping?100:46);q.render();}});
test('Phase two warns of a locked beam, allows a sidestep, and exposes the core',()=>{for(const dodge of [false,true]){const h=boot(),q=h.qa;q.start();q.enterCave();q.bossSet({x:0,z:0,health:480,action:'hunt',cooldown:0,sequence:2});q.set({x:0,z:10,health:100,invulnerable:0,y:0});q.render();const ordinaryGeometry=q.get().meshSize;q.updateBoss(.01);assert.equal(q.get().boss.action,'beam');assert.equal(q.get().boss.phaseAnnounced,true);assert.match(h.element('boss-action').textContent,/RAYO.*franja/);q.render();assert(q.get().meshSize>ordinaryGeometry,'The beam warning should appear in the world');if(dodge)q.set({x:5,z:10});q.updateBoss(1.5);assert.equal(q.get().health,dodge?100:28);assert.equal(q.get().boss.action,'exposed');assert.match(h.element('boss-action').textContent,/NÚCLEO EXPUESTO/);q.render();const before=q.get().boss.health;q.hitBoss();assert.equal(q.get().boss.health,before-42,'The exposed core should take 75% extra sword damage');assert(q.get().boss.timer>=4,'The opening must last long enough to charge a weapon');q.set({x:0,z:4,y:0,yaw:Math.PI});h.fire('attack','pointerdown',{pointerType:'mouse',pointerId:7});const exposedHealth=q.get().boss.health;q.update(3);assert.equal(q.get().boss.health,exposedHealth,'Sword transformation should not damage the boss');h.fire('attack','pointerup',{pointerType:'mouse',pointerId:7});q.attack();assert.equal(q.get().boss.health,exposedHealth-65,'Demonic hits retain the exposed core vulnerability');q.updateBoss(1.3);assert.notEqual(q.get().boss.action,'exposed');}});
test('Best completion time persists and only improves after a faster win',()=>{const h=boot(),q=h.qa;assert.equal(h.element('menu-record').textContent,'Mejor tiempo: —');q.start();q.clock(173.4);q.completeAdventure();assert.equal(q.get().state,'won');assert.equal(q.record(),173.4);assert.equal(Number(h.storage.get('isla-brava-adventure-best-time')),173.4);assert.equal(h.element('result-record').textContent,'¡Nuevo récord! 2:53');assert.equal(h.element('menu-record').textContent,'Mejor tiempo: 2:53');const second=boot({storage:Object.fromEntries(h.storage)}),s=second.qa;assert.equal(second.element('menu-record').textContent,'Mejor tiempo: 2:53');s.start();s.clock(210);s.completeAdventure();assert.equal(s.record(),173.4);assert.equal(second.element('result-record').textContent,'Mejor tiempo: 2:53');s.start();s.clock(120.5);s.completeAdventure();assert.equal(s.record(),120.5);assert.equal(second.element('hud-best').textContent,'2:00');});
test('Pause freezes the boss, hazards, healing and arrival banner',()=>{const h=boot(),q=h.qa;q.start();q.enterCave();q.bossSet({action:'rock',timer:1,lockX:0,lockZ:15});q.pause();const before=q.get();q.update(4);q.updateBoss(4);const after=q.get();assert.equal(after.boss.timer,before.boss.timer);assert.equal(after.boss.cooldown,before.boss.cooldown);assert.equal(after.intro,before.intro);assert.equal(after.health,before.health);assert.equal(after.elapsed,before.elapsed);q.resume();q.update(.04);assert(q.get().boss.timer<before.boss.timer);});
test('The cave has its own boundaries and hides the island merchants',()=>{const h=boot(),q=h.qa;q.start();q.enterCave();const p={x:0,z:0};for(let i=0;i<100;i++)q.moveBody(p,1,0,.42);assert(p.x<26);const n=q.get().npcs[0];q.set({x:n.x,z:n.z+2});q.openShop();assert.equal(q.get().state,'playing');assert.equal(q.get().shop,null);q.set({x:0,z:15});q.render();assert.equal(h.element('interact').hidden,true);});
test('Retrying the boss keeps equipment; beating the first boss unlocks the jungle',()=>{const h=boot(),q=h.qa;q.start();q.xp(20);const n=q.get().npcs.find(n=>n.kind==='armor');q.set({x:n.x,z:n.z+2});q.openShop();q.buyArmor('helmet');q.closeShop();for(let i=0;i<30;i++)q.defeat();q.set({health:1,invulnerable:0});q.damage();assert.equal(q.get().state,'lost');h.fire('replay','click');assert.equal(q.get().region,'cave');assert.equal(q.get().state,'playing');assert.equal(q.get().armor.length,1);assert.equal(q.get().health,100);assert.equal(q.get().score,300);assert.equal(q.get().boss.health,960);const xp=q.get().experience;for(let i=0;i<40;i++)q.hitBoss();assert.equal(q.get().state,'playing');assert.equal(q.campaignLevel(),2);assert.equal(q.get().experience,xp+50);q.hitBoss();assert.equal(q.get().experience,xp+50);q.start();assert.equal(q.get().region,'island');assert.equal(q.get().score,0);assert.equal(q.get().armor.length,0);assert.equal(q.get().boss,null);});
test('The boss preview is safe and returns to the original menu',()=>{const h=boot(),q=h.qa;q.showBossPreview();assert.equal(q.get().state,'preview');assert.equal(q.get().region,'cave');q.render();const size=q.get().meshSize;q.mobs([]);q.render();assert.equal(q.get().meshSize,size,'Island enemies appear inside the boss preview');q.update(10);assert.equal(q.get().health,100);assert.equal(q.get().score,0);assert.equal(q.get().boss.health,960);assert.equal(q.get().boss.maxHealth,960);h.key('Escape');assert.equal(q.get().state,'menu');assert.equal(q.get().region,'island');assert.equal(q.get().boss,null);q.render();});


test('Demonic sword lasts fifteen gameplay seconds, shows a countdown and restores the original model',()=>{
 const h=boot(),q=h.qa;q.start();q.mobs([]);const normalMesh=q.gearMesh(),normal=q.weaponFor();h.fire('attack','pointerdown',{pointerType:'touch',pointerId:31});q.update(2.99);assert.equal(q.demonicTime(),0);q.update(.01);assert.equal(q.demonicTime(),15);h.fire('attack','pointerup',{pointerType:'touch',pointerId:31});assert.equal(q.weaponFor().name,'Espada demoníaca');assert.equal(q.weaponDamage(q.weaponFor()),37);assert.match(h.element('weapon-detail').textContent,/37.*15 s/);assert(h.element('attack').classList.contains('demonic'));
 const demonMesh=q.gearMesh();assert(demonMesh.length>normalMesh.length);assert(demonMesh.every(Number.isFinite));let red=0,dark=0;for(let i=0;i<demonMesh.length;i+=11){if(demonMesh[i+8]>.8&&demonMesh[i+9]<.2)red++;if(demonMesh[i+8]<.1&&demonMesh[i+9]<.1&&demonMesh[i+10]<.15)dark++;}assert(red>=7);assert(dark>=10);q.render();
 q.update(4);assert.equal(q.demonicTime(),11);q.pause();q.update(20);assert.equal(q.demonicTime(),11);q.resume();q.update(10);assert.equal(q.demonicTime(),1);assert.match(h.element('weapon-detail').textContent,/1 s/);q.update(1);assert.equal(q.demonicTime(),0);assert.equal(q.weaponDamage(q.weaponFor()),24);assert.equal(q.weaponFor().name,normal.name);assert.equal(q.weaponFor().detail,normal.detail);assert.equal(q.gearMesh().length,normalMesh.length);assert(!h.element('attack').classList.contains('demonic'));q.render();
});
test('Demonic damage is exactly 37 with an upgraded sword; shop time freezes the transformation',()=>{
 const h=boot(),q=h.qa;q.start();q.xp(20);const n=q.get().npcs.find(n=>n.kind==='forge');q.set({x:n.x,z:n.z+2});q.openShop();assert(q.upgradeWeapon());q.closeShop();assert.equal(q.weaponDamage(q.weaponFor()),28);q.attack(true);assert.equal(q.weaponDamage(q.weaponFor()),37);assert.equal(q.weaponDamage(q.weaponFor(),true),37);q.openShop();assert.equal(q.get().state,'shop');q.update(20);q.updateDemonicSword(20);assert.equal(q.demonicTime(),15);q.closeShop();q.set({x:0,z:0,y:0});q.mobs([[0,-2]]);Object.assign(q.monsters()[0],{health:100,maxHealth:100});q.attack();assert.equal(q.monsters()[0].health,63);q.updateDemonicSword(15);assert.equal(q.weaponDamage(q.weaponFor()),28);assert.equal(q.get().weaponLevel,1);
});
test('Transformation carries into the cave and clears on game over, new games and menu',()=>{
 const h=boot(),q=h.qa;q.start();q.attack(true);q.updateDemonicSword(4);q.enterCave();assert.equal(q.demonicTime(),11);q.hitBoss();assert.equal(q.get().boss.health,923);q.bossSet({health:1});q.hitBoss();assert.equal(q.campaignLevel(),2);assert.equal(q.get().state,'playing');assert.equal(q.demonicTime(),0);q.start();q.attack(true);q.start();assert.equal(q.demonicTime(),0);q.attack(true);q.menu();assert.equal(q.demonicTime(),0);
});


test('Demonic sword has a 25-second cooldown from activation without blocking ordinary hits',()=>{
 const h=boot(),q=h.qa;q.start();q.mobs([[0,-2]]);const m=q.monsters()[0];Object.assign(m,{health:200,maxHealth:200});h.fire('attack','pointerdown',{pointerType:'touch',pointerId:41});q.updateCharge(3);h.fire('attack','pointerup',{pointerType:'touch',pointerId:41});assert.equal(q.demonicCooldown(),25);assert.match(h.element('attack-hint').textContent,/25 S/);q.updateDemonicSword(5);q.attack(true);assert.equal(q.demonicTime(),10);assert.equal(q.demonicCooldown(),20);q.attack();assert.equal(m.health,163);q.update(.5);
 h.fire('attack','pointerdown',{pointerType:'touch',pointerId:42});q.updateCharge(3);assert(q.charge().triggered);assert(!h.element('attack').classList.contains('charged'));assert.equal(q.demonicTime(),9.5);h.fire('attack','pointerup',{pointerType:'touch',pointerId:42});assert.equal(m.health,163);q.updateDemonicSword(9.5);assert.equal(q.demonicTime(),0);assert.equal(q.demonicCooldown(),10);assert.match(h.element('attack-hint').textContent,/10 S/);q.attack();assert.equal(m.health,139);q.update(.5);
 q.updateDemonicSword(9.49);assert(q.demonicCooldown()>0);q.attack(true);assert.equal(q.demonicTime(),0);q.updateDemonicSword(.02);assert.equal(q.demonicCooldown(),0);assert.match(h.element('attack-hint').textContent,/MANTENÉ 3 S/);h.fire('attack','pointerdown',{pointerType:'touch',pointerId:43});q.updateCharge(3);assert.equal(q.demonicTime(),15);assert.equal(q.demonicCooldown(),25);h.fire('attack','pointerup',{pointerType:'touch',pointerId:43});
});
test('Special cooldown freezes in pause and shops, survives teleport and resets with the run',()=>{
 const h=boot(),q=h.qa;q.start();q.mobs([]);q.attack(true);q.update(4);assert.equal(q.demonicCooldown(),21);q.pause();q.update(30);q.updateDemonicSword(30);assert.equal(q.demonicCooldown(),21);q.resume();const n=q.get().npcs.find(n=>n.kind==='forge');q.set({x:n.x,z:n.z+2});q.openShop();assert.equal(q.get().state,'shop');q.update(30);assert.equal(q.demonicCooldown(),21);q.closeShop();q.enterCave();assert.equal(q.demonicCooldown(),21);q.bossSet({health:1});q.hitBoss();assert.equal(q.demonicCooldown(),0);q.start();q.attack(true);q.start();assert.equal(q.demonicCooldown(),0);q.attack(true);q.menu();assert.equal(q.demonicCooldown(),0);
});


test('Graphics defaults to Medium and both selectors switch quality without changing the run',()=>{
 const h=boot({dpr:3}),q=h.qa;assert.equal(q.graphics(),'medium');assert.equal(h.element('graphics-menu-medium').getAttribute('aria-pressed'),'true');q.start();q.render();assert.equal(h.element('world').width,2176);const before=q.get();q.pause();h.fire('graphics-pause-high','click');assert.equal(q.graphics(),'high');q.render();assert.equal(h.element('world').width,2560);assert.equal(q.get().state,'paused');assert.equal(q.get().score,before.score);assert.deepEqual(q.get().player,before.player);assert.equal(q.get().meshSize,before.meshSize);assert.equal(h.element('graphics-menu-high').getAttribute('aria-pressed'),'true');assert.equal(h.storage.get('isla-brava-graphics'),'high');q.resume();q.enterCave();q.render();h.fire('graphics-pause-medium','click');assert.equal(q.graphics(),'medium');q.render();assert.equal(h.element('world').width,2176);assert.equal(q.get().region,'cave');assert.equal(q.get().boss.health,960);assert.equal(q.setGraphicsQuality('ultra'),false);
});
test('Saved graphics settings are restored and invalid values use Medium',()=>{
 const h=boot({storage:{'isla-brava-graphics':'high'}});assert.equal(h.qa.graphics(),'high');h.qa.render();h.fire('graphics-menu-medium','click');const next=boot({storage:Object.fromEntries(h.storage)});assert.equal(next.qa.graphics(),'medium');assert.equal(boot({storage:{'isla-brava-graphics':'invalid'}}).qa.graphics(),'medium');
});
test('A failed High shader leaves Medium playable and reports the unavailable option',()=>{
 const h=boot({failHigh:true,storage:{'isla-brava-graphics':'high'}}),q=h.qa;assert.equal(q.graphics(),'medium');assert.equal(h.element('graphics-menu-high').disabled,true);assert.match(h.element('graphics-pause-note').textContent,/no está disponible/);q.start();q.render();assert.equal(q.get().state,'playing');assert.equal(q.setGraphicsQuality('high'),false);assert.equal(q.graphics(),'medium');q.render();
});


test('Level two unlocks automatically after the golem and keeps equipment, XP and adventure time',()=>{
 const h=boot(),q=h.qa;q.start();q.xp(30);const forge=q.get().npcs.find(n=>n.kind==='forge');q.set({x:forge.x,z:forge.z+2});q.openShop();q.upgradeWeapon();q.closeShop();const armorer=q.get().npcs.find(n=>n.kind==='armor');q.set({x:armorer.x,z:armorer.z+2});q.openShop();q.buyArmor('helmet');q.closeShop();q.clock(120);q.enterCave();const xp=q.get().experience;q.hitBoss(9999);assert.equal(q.campaignLevel(),2);assert.equal(q.get().region,'island');assert.equal(q.get().state,'playing');assert.equal(q.get().score,0);assert.equal(q.get().elapsed,120);assert.equal(q.get().experience,xp+50);assert.equal(q.get().weaponLevel,1);assert.deepEqual(Array.from(q.get().armor),['helmet']);assert.equal(q.get().health,100);assert.equal(q.get().boss,null);assert.equal(q.record(),null);assert.equal(h.element('result').hidden,true);assert.match(h.element('arrival-title').textContent,/NIVEL 2/);assert.equal(q.poison().time,0);q.render();
});
test('Jungle generation places seven bridges and keeps forts, landmarks, enemies and healing out of rivers',()=>{
 const h=boot(),q=h.qa;q.start();for(let run=0;run<12;run++){q.enterJungle();assert.equal(q.bridges().length,7);assert(q.get().forts.every(f=>!q.nearJungleRiver(f.x,f.z,34)));assert(q.landmarks().every(s=>!q.nearJungleRiver(s.x,s.z,s.radius+8)));assert(q.monsters().every(m=>q.jungleWalkable(m.x,m.z,.65)&&!q.insideFort(m.x,m.z,3)));assert(q.get().kits.every(k=>q.jungleWalkable(k.x,k.z,.9)));for(const n of q.get().npcs){const f=q.get().forts.find(f=>f.id===n.fort);q.set({x:n.x,z:n.z+f.gateSide*2,y:0});assert(q.npcAccessible(n));}}q.render();q.setGraphicsQuality('high');q.render();
});
test('River banks block movement while both kinds of wooden bridges let players cross',()=>{
 const h=boot(),q=h.qa;q.start();q.enterJungle();let body={x:20,z:q.riverCenter(20)-15};for(let i=0;i<35;i++)q.moveBody(body,0,1,.42);assert(body.z<q.riverCenter(20)-7);assert(!q.jungleWalkable(20,q.riverCenter(20),.42));for(const bridge of [q.bridges()[2],q.bridges()[5]]){const vertical=bridge.sz>bridge.sx;body={x:bridge.x-(vertical?0:16),z:bridge.z-(vertical?17:0)};for(let i=0;i<35;i++)q.moveBody(body,vertical?0:1,vertical?1:0,.42);assert(vertical?body.z>bridge.z+12:body.x>bridge.x+12);}q.drawMap();
});
test('Jungle enemies have distinct silhouettes; vipers telegraph and apply non-stacking poison',()=>{
 const h=boot(),q=h.qa;q.start();q.enterJungle();assert.deepEqual([...new Set(q.monsters().map(m=>m.kind))].sort(),['panther','shaman','viper']);q.mobs([[0,-2.5]]);const m=q.monsters()[0];Object.assign(m,q.createMonster({x:0,z:-2.5},0),{attack:0});q.set({x:0,z:0,y:0,health:100,invulnerable:0});q.updateMonsters(.01);assert(m.windup>0);assert.equal(q.get().health,100);q.updateMonsters(.56);assert.equal(q.get().health,88);assert.equal(q.poison().time,5);q.venomHit(12,m);assert.equal(q.get().health,88);assert.equal(q.poison().time,5);q.updatePoison(2);assert.equal(q.get().health,82);q.pause();q.updatePoison(10);assert.equal(q.poison().time,3);q.resume();q.updatePoison(3);assert.equal(q.get().health,73);assert.equal(q.poison().time,0);q.render();
});
test('A dodged viper bite does not poison; medkits cure venom even at full health',()=>{
 const h=boot(),q=h.qa;q.start();q.enterJungle();q.mobs([[0,-2.5]]);const m=q.monsters()[0];Object.assign(m,q.createMonster({x:0,z:-2.5},0),{attack:0});q.set({x:0,z:0,y:0,invulnerable:0});q.updateMonsters(.01);q.set({x:5,z:0});q.updateMonsters(.56);assert.equal(q.get().health,100);assert.equal(q.poison().time,0);q.venomHit(12,m);assert.equal(q.poison().time,5);const kit=q.get().kits[0];q.set({x:kit.x,z:kit.z,y:0,health:100});q.updateMedkits(.01);assert.equal(q.poison().time,0);assert.equal(q.get().health,100);assert(q.get().kits[0].cooldown>0);assert.equal(h.element('poison-status').hidden,true);
});
test('Panthers warn and leap in a committed direction that can be sidestepped',()=>{
 for(const dodge of [false,true]){const h=boot(),q=h.qa;q.start();q.enterJungle();q.mobs([[0,-6]]);const m=q.monsters()[0];Object.assign(m,q.createMonster({x:0,z:-6},1),{attack:0,chargeCooldown:0});q.set({x:0,z:0,y:0,health:100,invulnerable:0});q.updateMonsters(.01);assert(m.windup>0);q.updateMonsters(.71);assert(m.pounceTime>0);if(dodge)q.set({x:4,z:0});for(let i=0;i<10;i++)q.updateMonsters(.05);assert.equal(q.get().health,dodge?100:78);q.render();}
});
test('Jungle shamans warn before a venom volley and their shots can be dodged',()=>{
 for(const dodge of [false,true]){const h=boot(),q=h.qa;q.start();q.enterJungle();q.mobs([[0,-10]]);const m=q.monsters()[0];Object.assign(m,q.createMonster({x:0,z:-10},2),{attack:0});q.set({x:0,z:0,y:0,health:100,invulnerable:0});q.updateMonsters(.01);assert(m.cast>0);assert.equal(q.enemyBolts().length,0);q.updateMonsters(.81);assert.equal(q.enemyBolts().length,3);assert(q.enemyBolts().every(b=>b.poison));if(dodge)q.set({x:5,z:0});for(let i=0;i<35;i++)q.updateEnemyBolts(.04);assert.equal(q.get().health,dodge?100:87);assert.equal(q.poison().time,dodge?0:5);q.render();}
});
test('Four jungle quests each award one distinct ancestral armor piece and preserve older magic',()=>{
 const h=boot(),q=h.qa;q.start();for(const kind of ['lake','ruins','tower','village']){const m=q.mission(kind);q.startMission(m);m.progress=m.goal;q.updateMissions(.01);}assert.equal(q.magicArmor().length,4);q.enterJungle();assert.equal(q.magicArmor().length,4);for(const [i,kind] of ['lake','ruins','tower','village'].entries()){const m=q.mission(kind);assert.match(m.name,/Orquídeas|Ceiba|Tambor|Jaguar/);q.startMission(m);if(kind==='village')assert(q.missionRaiders().every(m=>m.kind==='panther'));m.progress=m.goal;q.updateMissions(.01);assert.equal(q.ancestral().length,i+1);assert(q.get().armor.length<=5);q.updateMissions(.01);assert.equal(q.ancestral().length,i+1);}assert.equal(new Set(q.ancestral()).size,4);assert(q.gearMesh().every(Number.isFinite));q.render();
});
test('Level two reaches its own 350-point threshold and opens the jungle dungeon',()=>{
 const h=boot(),q=h.qa;q.start();q.enterJungle();assert.equal(q.get().goalScore,350);assert.equal(h.element('score-goal').textContent,350);assert.equal(h.element('score-track').getAttribute('aria-valuemax'),'350');assert.match(h.element('arrival-text').textContent,/350 puntos/);for(let i=0;i<34;i++)q.defeat();assert.equal(q.get().region,'island');assert.equal(q.get().score,340);assert(Math.abs(parseFloat(h.element('score-fill').style.width)-340/350*100)<.001);q.defeat();assert.equal(q.get().region,'cave');assert.equal(q.get().boss.kind,'basilisk');assert.equal(q.get().boss.health,1200);assert.equal(q.get().score,350);assert.equal(h.element('score-fill').style.width,'100%');assert.match(h.element('arrival-text').textContent,/350 puntos/);assert.match(h.element('boss-name').textContent,/BASILISCO/);assert.match(h.element('arrival-title').textContent,/TEMPLO/);q.render();
});
test('Every weapon damages the jungle boss, whose venom marks become timed hazards',()=>{
 for(let avatar=0;avatar<3;avatar++){const h=boot(),q=h.qa;q.avatar(avatar);q.start();q.enterJungle();q.enterCave();const b=q.get().boss;q.set({x:b.x,z:b.z+4,y:0,yaw:Math.PI,invulnerable:0});q.attack();for(let i=0;i<20;i++)q.updateWeapons(.03);assert(q.get().boss.health<1200);assert(q.get().boss.health>0);q.bossSet({action:'venom',timer:1,marks:[{x:10,z:10}]});q.set({x:10,z:10,health:100,invulnerable:0});q.updateBoss(.5);assert.equal(q.get().health,100);q.updateBoss(.51);assert.equal(q.get().hazards[0].kind,'venomPool');assert.equal(q.get().health,88);assert.equal(q.poison().time,5);q.pause();const timer=q.get().hazards[0].life;q.updateBoss(10);assert.equal(q.get().hazards[0].life,timer);q.resume();q.set({x:-10,z:10});q.updateBoss(6.1);assert(!q.get().hazards.some(h=>h.kind==='venomPool'));q.render();}
});
test('The basilisk phase-two tail and leap are announced, avoidable and expose its chest',()=>{
 for(const dodge of [false,true]){const h=boot(),q=h.qa;q.start();q.enterJungle();q.enterCave();q.bossSet({x:0,z:0,health:600,action:'tail',timer:1,cooldown:10});q.set({x:0,z:5,health:100,invulnerable:0,y:dodge?1.2:0});q.updateBoss(.5);assert.equal(q.get().health,100);assert.match(h.element('boss-action').textContent,/COLETAZO/);q.updateBoss(.51);assert.equal(q.get().health,dodge?100:52);assert(q.get().boss.phaseAnnounced);q.updateBoss(1.6);q.bossSet({action:'pounce',timer:1,lockX:0,lockZ:12});q.set({x:0,z:12,health:100,invulnerable:0,y:0});q.updateBoss(.5);assert.match(h.element('boss-action').textContent,/SALTO/);q.updateBoss(.51);if(dodge)q.set({x:8,z:12});q.updateBoss(.51);assert.equal(q.get().health,dodge?100:58);assert.equal(q.get().boss.action,'exposed');const hp=q.get().boss.health;q.hitBoss(24);assert.equal(q.get().boss.health,hp-42);q.render();}
});
test('Only the basilisk completes the adventure; jungle deaths retry the same level with gear',()=>{
 const h=boot(),q=h.qa;q.start();q.xp(20);const n=q.get().npcs.find(n=>n.kind==='armor');q.set({x:n.x,z:n.z+2});q.openShop();q.buyArmor('boots');q.closeShop();q.enterCave();q.hitBoss(9999);assert.equal(q.campaignLevel(),2);q.set({health:1,invulnerable:0});q.damage();assert.equal(q.get().state,'lost');h.fire('replay','click');assert.equal(q.campaignLevel(),2);assert.equal(q.get().region,'island');assert.equal(q.get().health,100);assert(q.get().armor.includes('boots'));q.enterCave();q.set({health:1,invulnerable:0});q.damage(50);h.fire('replay','click');assert.equal(q.get().boss.kind,'basilisk');assert.equal(q.get().boss.health,1200);q.hitBoss(9999);assert.equal(q.get().state,'won');assert.equal(q.campaignLevel(),2);q.start();assert.equal(q.campaignLevel(),1);assert.equal(q.ancestral().length,0);assert.equal(q.get().armor.length,0);
});

console.log(`${passed} passed, ${failed} failed.`);process.exitCode=failed?1:0;
